# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\开发\真-伪春菜\plugins\mymusic\music.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 578)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.songsList = QtWidgets.QListWidget(self.centralwidget)
        self.songsList.setGeometry(QtCore.QRect(10, 60, 281, 321))
        self.songsList.setStyleSheet("")
        self.songsList.setObjectName("songsList")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(130, 490, 41, 41))
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(11, 11, 264, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.searchBox = QtWidgets.QLineEdit(self.splitter)
        self.searchBox.setStyleSheet("")
        self.searchBox.setObjectName("searchBox")
        self.searchButton = QtWidgets.QPushButton(self.splitter)
        self.searchButton.setObjectName("searchButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 400, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.songSlider = QtWidgets.QSlider(self.centralwidget)
        self.songSlider.setGeometry(QtCore.QRect(10, 440, 271, 22))
        self.songSlider.setOrientation(QtCore.Qt.Horizontal)
        self.songSlider.setObjectName("songSlider")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(230, 490, 41, 41))
        self.nextButton.setText("")
        self.nextButton.setObjectName("nextButton")
        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        self.previousButton.setGeometry(QtCore.QRect(30, 490, 41, 41))
        self.previousButton.setText("")
        self.previousButton.setObjectName("previousButton")
        self.soundSlider = QtWidgets.QSlider(self.centralwidget)
        self.soundSlider.setGeometry(QtCore.QRect(140, 460, 141, 21))
        self.soundSlider.setOrientation(QtCore.Qt.Horizontal)
        self.soundSlider.setObjectName("soundSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "音乐播放器"))
        self.searchButton.setText(_translate("MainWindow", "检索"))
        self.label.setText(_translate("MainWindow", "歌曲名字"))
        self.label_2.setText(_translate("MainWindow", "总时长"))
